# Generated by Django 4.2.2 on 2023-06-26 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='appointments',
            new_name='appointment',
        ),
    ]
