# Generated by Django 4.2.2 on 2023-06-26 08:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_rename_appointments_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
    ]
