# Generated by Django 4.2.2 on 2023-06-26 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_appointment_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='time',
            new_name='Appointed Time',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='Appointment Date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='fname',
            new_name='First Name',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='gender',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='lname',
            new_name='Last Name',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='mobile',
            new_name='Mobile No.',
        ),
    ]
