# Generated by Django 4.2.2 on 2023-06-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_rename_age_appointment_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Last Name',
            new_name='lname',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Appointed Time',
            field=models.TimeField(),
        ),
    ]
