# Generated by Django 4.2.2 on 2023-06-26 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_rename_last_name_appointment_lname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='Appointment Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='First Name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='Mobile No.',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='Appointed Time',
            new_name='time',
        ),
    ]
