# Generated by Django 4.2.2 on 2023-06-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_appointment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(unique_for_date=True),
        ),
    ]
