# Generated by Django 4.2.2 on 2023-06-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0008_alter_appointment_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('speciality', models.CharField(max_length=25)),
            ],
        ),
    ]
