# Generated by Django 4.2.2 on 2023-06-27 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0009_doctors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='doctors',
            new_name='doctor',
        ),
    ]
