# Generated by Django 4.2.2 on 2023-06-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0010_rename_doctors_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(max_length=50),
        ),
    ]
