# Generated by Django 4.2.2 on 2023-06-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0011_alter_doctor_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
