# Generated by Django 4.2.2 on 2023-06-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0012_doctor_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.UUIDField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.UUIDField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
