# Generated by Django 4.2.2 on 2023-06-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0014_alter_appointment_id_alter_doctor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.UUIDField(default='0', unique=True)),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('doc_name', models.CharField(default='', max_length=60)),
                ('doc_type', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='doc_name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doc_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
