# Generated by Django 4.2.2 on 2023-06-29 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0015_patient_appointment_doc_name_appointment_doc_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='doc_type',
            new_name='doc_id',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='doc_type',
            new_name='doc_id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='doc_name',
        ),
    ]
