# Generated by Django 4.2.2 on 2023-06-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0017_remove_patient_id_alter_patient_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='lname',
        ),
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
