# Generated by Django 4.2.2 on 2023-07-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0019_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('pid', models.UUIDField(auto_created=True, default='', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('doc_id', models.CharField(default='', max_length=50)),
                ('doc_name', models.CharField(default='', max_length=50)),
                ('doc_spec', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
