# Generated by Django 4.2.2 on 2023-07-13 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0020_history'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='history',
            new_name='historie',
        ),
    ]
